settings:
  log_mode: text
  log_level: INFO
  output_mode: cli
  update_interval: 300

tickers:
  - ADANIPORTS.NS
  - HDFCLIFE.NS

exchanges:
  huobipro:
    required:
      enabled: true
  binance:
    required:
      enabled: true

indicators:
  rsi:
    - enabled: true
      alert_enabled: false
      alert_frequency: once
      signal:
        - rsi
      hot: 30
      cold: 70
      candle_period: 1h
      period_count: 50
    - enabled: true
      alert_enabled: true
      alert_frequency: once
      signal:
        - rsi
      hot: 30
      cold: 70
      candle_period: 5m
      period_count: 14
  stoch_rsi:
    - enabled: true
      alert_enabled: true
      alert_frequency: once
      signal:
        - stoch_rsi
      hot: 20
      cold: 80
      candle_period: 5m
      period_count: 14
  momentum:
    - enabled: true
      alert_enabled: false
      alert_frequency: once
      signal:
        - momentum
      hot: 0
      cold: 0
      candle_period: 1d
      period_count: 10
    - enabled: true
      alert_enabled: false
      alert_frequency: once
      signal:
        - momentum
      hot: 0
      cold: 0
      candle_period: 1h
      period_count: 12
  macd:
    - enabled: true
      alert_enabled: false
      alert_frequency: once
      signal:
        - macd
      hot: 20
      cold: 80
      candle_period: 15m
    - enabled: true
      alert_enabled: false
      alert_frequency: once
      signal:
        - macdsignal
      hot: 0
      cold: 0
      candle_period: 15m
  obv:
    - enabled: false
  mfi:
    - enabled: true
      alert_enabled: true
      alert_frequency: once
      signal:
        - mfi
      hot: 20
      cold: 80
      candle_period: 5m
      period_count: 14
  ichimoku:
    - enabled: false

informants:
  ema:
    - enabled: true
      signal:
        - ema
      candle_period: 1d
      period_count: 10
    - enabled: true
      signal:
        - ema
      candle_period: 1d
      period_count: 30

crossovers:
  std_crossover:
    - enabled: true
      alert_enabled: true
      alert_frequency: once
      key_indicator: ema
      key_indicator_index: 0
      key_indicator_type: informants
      key_signal: ema
      crossed_indicator: ema
      crossed_indicator_index: 1
      crossed_indicator_type: informants
      crossed_signal: ema
    - enabled: true
      alert_enabled: true
      alert_frequency: once
      key_indicator: macd
      key_indicator_index: 0
      key_indicator_type: indicators
      key_signal: macd
      crossed_indicator: macd
      crossed_indicator_index: 1
      crossed_indicator_type: indicators
      crossed_signal: macdsignal

notifiers:
  gmail:
    required:
      username: vikasmahato0@gmail.com
      password: 9.22576e+19
      destination_emails:
        - vikasmahato0@gmail.com
    optional:
      parse_mode: html
      template: "[{{analysis.config.candle_period}} / {{analysis.config.period_count}}] {{exchange}}-{{market}}-{{indicator}}-{{indicator_number}} is {{status}}! ({{values}}){{ '\\n' -}}"